import type { BatteryPackPreset, DevicePreset } from './types'

export const batteryPackPresets: BatteryPackPreset[] = [
  {
    id: 'lifepo4-12v-100ah',
    label: '12.8V 100Ah LiFePO₄',
    chemistryId: 'lifepo4',
    voltage: 12.8,
    capacityAh: 100,
    referenceWh: 1280,
    costTier: 'mid',
  },
  {
    id: 'lifepo4-24v-50ah',
    label: '25.6V 50Ah LiFePO₄',
    chemistryId: 'lifepo4',
    voltage: 25.6,
    capacityAh: 50,
    referenceWh: 1280,
    costTier: 'premium',
  },
  {
    id: 'liion-3s-10ah',
    label: '11.1V 10Ah Li-ion (3S)',
    chemistryId: 'liion',
    voltage: 11.1,
    capacityAh: 10,
    referenceWh: 111,
    costTier: 'budget',
  },
  {
    id: 'liion-4s-20ah',
    label: '14.8V 20Ah Li-ion (4S)',
    chemistryId: 'liion',
    voltage: 14.8,
    capacityAh: 20,
    referenceWh: 296,
    costTier: 'mid',
  },
  {
    id: 'sla-12v-7ah',
    label: '12V 7Ah SLA',
    chemistryId: 'sla',
    voltage: 12,
    capacityAh: 7,
    referenceWh: 84,
    costTier: 'budget',
  },
  {
    id: 'sla-12v-20ah',
    label: '12V 20Ah SLA',
    chemistryId: 'sla',
    voltage: 12,
    capacityAh: 20,
    referenceWh: 240,
    costTier: 'mid',
  },
  {
    id: 'nimh-12v-10ah',
    label: '12V 10Ah NiMH',
    chemistryId: 'nimh',
    voltage: 12,
    capacityAh: 10,
    referenceWh: 120,
    costTier: 'premium',
  },
  {
    id: 'lifepo4-48v-100ah',
    label: '51.2V 100Ah LiFePO₄ rack',
    chemistryId: 'lifepo4',
    voltage: 51.2,
    capacityAh: 100,
    referenceWh: 5120,
    costTier: 'premium',
  },
]

export const devicePresets: DevicePreset[] = [
  { id: 'led-strip', label: 'LED strip (5m)', powerW: 24, hours: 6, quantity: 1 },
  { id: 'mini-fridge', label: 'Mini fridge', energyWh: 120, quantity: 1 },
  { id: 'router', label: 'Wi-Fi router', powerW: 12, hours: 24, quantity: 1 },
  { id: 'cpap', label: 'CPAP machine', powerW: 90, hours: 8, quantity: 1 },
  { id: 'laptop', label: '65W laptop', powerW: 65, hours: 4, quantity: 1 },
  { id: 'phone', label: 'Phone charging', energyWh: 15, quantity: 2 },
  { id: 'drone', label: 'Drone charger', powerW: 150, hours: 1, quantity: 1 },
  { id: 'pump', label: 'Water pump', powerW: 80, hours: 2, quantity: 1 },
]
